friends/urls.py
from django.conf.urls import url
from .views import index, tambah_POST

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tambahkan-teman', tambah_POST, name='tambah_POST')
]

sosialmedia/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import update_status.urls as update_status
import statistic.urls as statistic
import user_profile.urls as user_profile
import update_status.urls as update_status
import friends.urls as friends
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update_status/', include(update_status,namespace='update_status')),
	url(r'^statistic/', include(statistic,namespace='statistic')),
	url(r'^user_profile/', include(user_profile,namespace='user_profile')),
	url(r'^$', RedirectView.as_view(permanent=True,   url='/update_status/')),
    url(r'^friends/', include(friends, namespace='friends'))
]

statistic/urls.py
from django.conf.urls import url
from .views import index,stat1
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^stat1',stat1,name='stat1')
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status, postdelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^postdelete/(?P<id_status>\d+)/$', postdelete, name='postdelete'),
]

user_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

friends/models.py
from django.db import models

# Create your models here.

class Data_teman(models.Model):
    nama = models.CharField(max_length=27)
    url = models.URLField(max_length=27)
    tanggal_dibuat = models.DateTimeField(auto_now_add=True)

statistic/models.py
from django.db import models

# Create your models here.

update_status/models.py
from django.db import models
from django.db import models

class Todo(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

user_profile/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    gender = models.TextField()
    description = models.TextField()
    birthday = models.DateTimeField()

friends/forms.py
from django import forms

class Form_teman(forms.Form):
    attrs = {
        'class' : 'input_form',
        'placeholder' : '> Nama',
        'id' : 'nama'
    }
    attrs2 = {
        'class' : 'input_form',
        'placeholder' : '> URL',
        'id' : 'url'
    }
    pesan_error = {
        'required' : 'harap di isi'
    }
    nama = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=attrs), error_messages=pesan_error)
    url  = forms.URLField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=attrs2), error_messages=pesan_error)

update_status/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    status_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'whats going on?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

friends/views.py
from django.shortcuts import render, redirect
from .forms import Form_teman
from .models import Data_teman

# Create your views here.
kam = {}
html = 'index.html',

def index(request):
    kam['form_teman'] = Form_teman
    tampilkan_daftar(request)
    return render(request, html, kam)

def tambah_POST(request):
    #if  request.method == 'POST':       coba aja komen ini. nanti dia multivaluedictkey error
    form = Form_teman(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        kam['nama'] = request.POST['nama']
        kam['url'] = request.POST['url']
        data = Data_teman(nama=kam['nama'], url=kam['url'])
        data.save()
        return redirect('/friends/')
    else:
        return redirect('/friends/')

def tampilkan_daftar(request):
    data = Data_teman.objects.all()
    kam['data'] = data

statistic/views.py
from django.shortcuts import render
from update_status.models import Todo
from friends.models import Data_teman

# Create your views here.
def index(request):
	jumlahstatus = Todo.objects.count();
	jumlahteman = Data_teman.objects.count(); 
	postinganteratas = Todo.objects.last();
	response = {'name' : 'Lee Jong-suk','jumlahstatus':jumlahstatus,'jumlahteman':jumlahteman,'postinganteratas':postinganteratas}
	return render(request,'statistic.html',response)

def stat1(request):
	jumlahstatus = Todo.objects.count();
	jumlahteman = Data_teman.objects.count();
	postinganteratas = Todo.objects.last();
	response = {'name' : 'Lee Jong-suk','jumlahstatus':jumlahstatus,'jumlahteman':jumlahteman,'postinganteratas':postinganteratas}
	return render(request,'statistic1.html',response)

update_status/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):
    response['author'] = "Lee Jong-suk" #TODO Implement yourname
    todo = Todo.objects.order_by('-id')
    response['todo'] = todo
    html = 'update.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_status(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        todo = Todo(status=response['status'])
        todo.save()
        return HttpResponseRedirect('/update_status/')
    else:
        return HttpResponseRedirect('/update_status/')

def postdelete(request,id_status):
    status = Todo.objects.get(pk = id_status)
    status.delete()
    return HttpResponseRedirect('/update_status/')

user_profile/views.py
from django.shortcuts import render
from datetime import datetime, date

# Create your views here.
profile_name = 'Lee Jong-suk' #TODO implement your name here
birth_date = date(1989,9,14) #TODO implement your birthday
birthdate = birth_date.strftime('%d %B %Y')
gender = 'Male' #TODO implement your gender
email = 'jongsuklee@gmail.com' #TODO implement your email
desc_profile = "A desperate ninja"
#TODO implement your expertise minimal 3
expert = ["Actor", "Model", "Oppa"]

response = {}
def index(request):
    response['author'] = "Mona Natasha"
    response['Name'] = profile_name
    response['Birthday'] = birthdate
    response['Gender'] = gender
    response['expertise'] = expert
    response['Email'] = email
    response['Description'] = desc_profile
    return render(request, 'user_profile/user_profile.html', response)

friends/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}

  <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet'>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Meera+Inimai|Josefin+Sans|Raleway" rel="stylesheet">
  <link href="{% static 'style.css' %}" rel='stylesheet'>
<div class='container'>
      <h3 class='judul'>Add Friend</h3>

      <form method='POST' action='tambahkan-teman'>
          {% csrf_token %}
          <div class='flex'>
              <div class='icon_container'><i class="fa fa-user-circle" aria-hidden="true"></i></div>
              {{ form_teman.nama }}
          </div>
          <div class='flex'>
              <div class='icon_container'><i class="fa fa-external-link" aria-hidden="true"></i></div>
              {{ form_teman.url }}
          </div>

          <section class='tombol'>
            <button id=submit type="submit">Tambah</button>
          </section>
      </form>

      <hr>

    <h3 class='judul'>Friends List</h3>
    <section>
            {% load tz %}
            {% if data %}
                {% for i in data %}
                <div class='flex2'>
                    <div class='bagian'>{{ i.nama }}</div>
                    {% if 'http' in i.url %}
                      <a class='bagian' href='{{ i.url }}' target="_blank"  >{{ i.url }}</a>
                    {% else %}
                      <a class='bagian' href='http://{{ i.url }}' target="_blank"  >{{ i.url }}</a>
                    {% endif %}
                    <div class='bagian'>ditambahkan {{ i.tanggal_dibuat|timezone:'Asia/Jakarta'|date:'d M Y H:i:s'}}</div>
                </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Tidak ada data teman</strong>
            </div>
            {% endif %}
    </section>
</div>

  {% endblock %}

statistic/templates/statistic.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}" />
<div class="container">
<img src="{% static 'images/jongsuk.jpg' %}" alt="Lee Jongsuk" width="200" height="200" class="img-circle" id="big-jongsuk"> 
<h1 style="text-align: center;">{{ name }}</h1>

<div class="col-sm-6" >
	<span class="glyphicon glyphicon-list" aria-hidden="true"></span>
	Posts : {{ jumlahstatus }}
</div>
<div class="col-sm-6" >
	<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	Friends : {{ jumlahteman }}
</div>
<div class="" style="padding: 30px;font-size: 25px;">
	Latest Post<br>
	{% if postinganteratas %}
	<img src="{% static 'images/jongsuk.jpg' %}" alt="Lee Jongsuk" width="100" height="100" style="padding: 20px;" class="img-circle" id="small-jongsuk"> {{ name }} <br>
	<h2 class="status">{{ postinganteratas.status }}</h2>
	<h6 class="tanggal">{{ postinganteratas.created_date }}</h6>
	{% else %}
	<p>No Posts!</p>
	{% endif %}
</div>
<a href="/statistic/" style="padding: 30px;">Theme 1</a>
<a href="stat1/" style="padding: 30px;">Theme 2</a>
</div>
{% endblock %}

statistic/templates/statistic1.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/statistic1.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div style="font-size: 24px;">
<img src="{% static 'images/jongsuk.jpg' %}" alt="Lee Jongsuk" width="150" height="150" style="padding: 20px;" class="img-circle"> 
&nbsp;&nbsp;&nbsp;{{ name }}
</div>

<div class="col-sm-6" >
	<span class="glyphicon glyphicon-list" aria-hidden="true"></span>
	Posts : {{ jumlahstatus }}
</div>
<div class="col-sm-6" >
	<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	Teman : {{ jumlahteman }}
</div>
<div class="container-fluid" id="fluida" style="padding: 10px;font-size: 25px;">
	Post Teratas<br>
	{% if postinganteratas %}
	<img src="{% static 'images/jongsuk.jpg' %}" alt="Lee Jongsuk" width="100" height="100" style="padding: 20px;" class="img-circle"> {{ name }} <br>
	<h2 style="padding: 0;">{{ postinganteratas.status }}</h2>
	<h6>{{ postinganteratas.created_date }}</h6>
	{% else %}
	<p>No Posts!</p>
	{% endif %}
</div>
<div class="coba">
<a href="/statistic/" style="padding: 20px;">Theme 1</a>
<a href="stat1/" style="padding: 20px;">Theme 2</a>
</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<link href="https://fonts.googleapis.com/css?family=Open+Sans|Meera+Inimai|Josefin+Sans|Raleway" rel="stylesheet">
<style>
* {
  margin: 0;
  padding: 0;
}

html,
body {
  height: 100%;
}

#wrap {
  min-height: 100%;
}

#main {
  overflow: auto;
  padding-bottom: 180px;
  /* must be same height as the footer */
}
#footer{
  padding: 20px;
}

body:before {
  content: "";
  height: 100%;
  float: left;
  width: 0;
  margin-top: -32767px;
}
.navbar-brand{
	margin-top: -1.5%;
  font-size: 10px;
  font-family:"Meera Inimai";
  color: #EFEDF4;
}

@media (max-width: 768px){
	.navbar-brand{
		margin-top: 2px;
	}
}

.navfont{
	margin-top: -3px;
  font-size: 17px;
  font-family: "Open Sans";
  color: #EFEDF4;
}
</style>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="SosialMedia">
    <meta name="author" content="PPW B Class Group 6">
    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>
        SosialMedia
    </title>
</head>

<body style="background-image: url('http://efdreams.com/data_images/dreams/paper/paper-10.jpg')">
    <header>
    <div class="page-title">
    <nav class="nav" style="background-color: #C5C4C6;border-color: #0080FF;">
        <div class="container-fluid">
          <div class="navbar-header" style="">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar" style="background-color: white;"></span>
              <span class="icon-bar" style="background-color: white;"></span>
              <span class="icon-bar" style="background-color: white;"></span>
            </button>
            <a class="navbar-brand" href="#" style="">SosialMedia</a>
      </div>
    <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav" style="background-color: #C5C4C6;">
          <li><a href="/update_status/" class="navfont">Status</a></li>
          <li><a href="/user_profile/" class="navfont">Profile</a></li>
          <li><a href="/friends/" class="navfont">Friends</a></li>
          <li><a href="/statistic/" class="navfont">Stats</a></li>

    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <p id="footer", style="text-align: center;">&copy; Made by Group 6 PPW (Class B)</p>
    </footer>

    <!-- Jquery n Bootstrap Script -->

update_status/templates/update.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Droid+Sans|Roboto|Open+Sans|Raleway|Mukta:600|Meera+Inimai" rel="stylesheet">
<section>
  <div class="container" id="kontener" >
    <div class="col-sm-8">
        <div class="panel panel-white post panel-shadow">
<form class="containerform font2"id="form" method="POST" action="{% url 'update_status:add_status' %}">
    <h2 class="title">Update Status</h2>
    {% csrf_token %}
    {{ todo_form }}

    <br>
    <input class="button fontbutton"id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Update" style="background-color: dodgerBlue">
</form>
</div>
</div>
</div>
</section>

{% if todo %}
    {% for data in todo %}
<div class="container" id="kontener" >
  <div class="col-sm-8">
      <div class="panel panel-white post panel-shadow">
          <div class="post-heading">
            <div class="pull-left image">
                <img src="{% static "images/jongsuk.jpg" %}" class="img-circle avatar" alt="user profile image">
            </div>
            <div class="pull-left meta">
                <div class="title h5 fontnama">
                    {{author}}
                </div>
                <h6 class="text-muted time font2">{{data.created_date}}</h6>
            </div>
          </div>
          <div class="post-description font2">
              <p>{{data.status}}</p>
              <div class="stats">
                <a href= "/update_status/postdelete/{{ data.id }}">
                  <img src= "{% static "images/garbage.png" %}" style="width:25px;height:25px;">
                </a>
              </div>
          </div>

      </div>
  </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

user_profile/templates/user_profile/user_profile.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/user_profile.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans|Meera+Inimai|Josefin+Sans|Raleway" rel="stylesheet">
<section class="container">
<h3 align = "center" class="title"> Profile</h3><br>
<center>
<img class = "img-circle" src="{% static "images/jongsuk.jpg" %}" alt = "Lee Jong-suk">
</center><br>
<h4 align = "center" , class="font1">{{ Name }}</h4><br>
<div>
<center>
<table align = "center"  width="500" cellspacing = "40" cellpadding="40" class="font2">
<tr>
	<td class="fonttable" align = "left">Birthday</td>
	<td class="fonttable" align = "left">{{ Birthday }}</td>
</tr>
<tr >
	<td class="fonttable" align = "left">Gender</td>
	<td class="fonttable" align = "left">{{ Gender }}</td>
</tr>
<tr>
	<td class="fonttable" align = "left">Expertise</td>
	<td align = "left">
		<ul>
			{% for ii in expertise %}
				<li class="exp fonttable">{{ ii }}</li>
			{% endfor %}
		</ul>
	</td>
</tr>
<tr>
	<td class="fonttable" align = "left">Description</td>
	<td class="fonttable" align = "left">{{ Description }}</td>
</tr>
<tr>
	<td class="fonttable" align = "left">Email</td>
	<td class="fonttable" align = "left">{{ Email }}</td>
</tr>
</div>
</table>
</section>
</center>

{% endblock %}